QuizDerFlandriens/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using QuizDerFlandriens.Models;
using QuizDerFlandriens.Models.Repositories;

namespace QuizDerFlandriens.Controllers
{
    public class QuizController : Controller
    {
        private IQuizRepo quizRepo;
        private UserManager<Person> userManager;
        public static int score;
        public static int currentQuestion = 0;
        public static int potentialScore;
        public static Guid QuizId;
        public static List<Question> wrongQuestions = new List<Question>();

        public QuizController(IQuizRepo quizRepo, UserManager<Person> userManager)
        {
            this.quizRepo = quizRepo;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Quizzes()
        {
            QuizController.score = 0;
            QuizController.currentQuestion = 0;
            QuizController.potentialScore = 0;
            QuizController.wrongQuestions = new List<Question>();

            IEnumerable<Quiz> quizzes = null;
            quizzes = await quizRepo.GetAllQuizzesAsync();
            foreach (Quiz quiz in quizzes)
            {
                foreach (Question question in quiz.Questions)
                {
                    IEnumerable<Answer> answersEnum = await quizRepo.GetAllAnswersByQuestionId(question.Id);
                    List<Answer> answers = answersEnum.ToList();
                    question.Answers = answers;
                }
            }
            return View(quizzes);
        }
        [Authorize(Roles = "Player, Admin")]
        public async Task<IActionResult> QuizScores(Guid id, string quizName)
        {
            var results = await quizRepo.GetAllResultsByQuizId(id);
            ViewData["QuizName"] = quizName;
            return View(results);
        }
        [Authorize(Roles = "Player, Admin")]
        public IActionResult PlayQuiz(Guid id)
        {
            QuizController.QuizId = id;
            return RedirectToAction(nameof(ShowQuestion));
        }
        [Authorize(Roles = "Player, Admin")]
        public async Task<IActionResult> ShowQuestion()
        {
            IEnumerable<Question> questions = await quizRepo.GetAllQuestionsByQuizId(QuizController.QuizId);
            
            List<Question> questionsList = questions.ToList();
            List<Question> wrongQuestions = new List<Question>();
            //Antwoorden checken of question inorde is
            foreach (Question q in questionsList)
            {
                IEnumerable<Answer> answers = await quizRepo.GetAllAnswersByQuestionId(q.Id);

                bool error = false;
                if (answers.Count() < 2)
                {
                    error = true;
                }
                else
                {
                    int countTrues = 0;
                    bool onlyDiscriptions = true;
                    bool onlyPhotos = true;
                    foreach (Answer answer in answers)
                    {
                        if (answer.Correct.ToString() == "True")
                        {
                            countTrues = countTrues + 1;
                        }
                        if (answer.Description == null)
                        {
                            onlyDiscriptions = false;
                        }
                        if (answer.FotoURL == null)
                        {
                            onlyPhotos = false;
                        }
                    }
                    if (!onlyDiscriptions && !onlyPhotos)
                    {
                        error = true;
                    }
                    if (countTrues == 0)
                    {
                        error = true;
                    }
                    else if (countTrues > 1)
                    {
                        error = true;
                    }
                }
                if (error)
                {
                    wrongQuestions.Add(q);
                }
            }

            foreach (Question q in wrongQuestions)
            {
                questionsList.Remove(q);
            }

            double progressPercentage = Math.Floor((double.Parse(QuizController.currentQuestion.ToString())/float.Parse(questionsList.Count().ToString()))*100);
            ViewData["ProgressPercentage"] = progressPercentage;
            ViewData["PotentialScore"] = QuizController.potentialScore;
            ViewData["Score"] = QuizController.score;
            if(QuizController.currentQuestion == questionsList.Count())
            {
                return RedirectToAction(nameof(EndQuiz));
            }
            Question question = await quizRepo.GetQuestionForIdAsync(questionsList[QuizController.currentQuestion].Id);
            return View(question);
        }
        [Authorize(Roles = "Player, Admin")]
        public async Task<IActionResult> CheckAnswer(bool isCorrect, Guid id)
        {
            Question question = await quizRepo.GetQuestionForIdAsync(id);
            if (isCorrect)
            {
                QuizController.score = QuizController.score + question.Answers.Count();
            }
            else
            {
                QuizController.wrongQuestions.Add(question);
            }
            QuizController.potentialScore = QuizController.potentialScore + question.Answers.Count();
            QuizController.currentQuestion++;
            return RedirectToAction(nameof(ShowQuestion));
        }
        [Authorize(Roles = "Player, Admin")]
        public async Task<IActionResult> EndQuiz()
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            Quiz quiz = await quizRepo.GetQuizForIdAsync(QuizController.QuizId);
            Result result = new Result()
            {
                Id = Guid.NewGuid(),
                Score = QuizController.score,
                QuizId = QuizController.QuizId,
                Quiz = quiz
            };
            string personId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Person person = await userManager.FindByIdAsync(personId);
            result.Person = person;
            ViewData["MaxScore"] = QuizController.potentialScore;
            ViewData["PersonName"] = person.Name;
            ViewData["QuizName"] = quiz.Subject;
            ViewData["WrongQuestions"] = QuizController.wrongQuestions;
            var created = await quizRepo.AddResult(result);
            if (created == null)
            {
                throw new Exception("Invalid Entry");
            }
            return View(result);
        }

    }
}

QuizDerFlandriens/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizDerFlandriens</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 bg-white">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Quiz" asp-action="Quizzes">QuizDerFlandriens</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="Quizzes">Home</a>
                        </li>
                        @using Microsoft.AspNetCore.Identity
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Quizzes">
                                    Quiz Management
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - QuizDerFlandriens - Robbe De Clercq - 2MCT-AI
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>